[package]
name = "dapper"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = { version = "*" }
tree-sitter-dapper = { path = "tree-sitter" }
indexmap = "*"

[build-dependencies]
cc = "*"
